# Generated by Django 3.1.8 on 2021-06-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard_ocr', '0002_auto_20210414_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.CharField(default='', max_length=90000),
        ),
    ]
